services:
  web:
    build: .
    command: python manage.py runserver 
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
