# Generated by Django 5.0.7 on 2024-07-15 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя магазина')),
                ('open', models.BooleanField(default=True, verbose_name='Открыт')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Готовится'), ('delivering', 'Доставка'), ('completed', 'Завершен')], default='preparing', max_length=10, verbose_name='Статус')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shop', verbose_name='Магазин')),
            ],
        ),
    ]
